import { contextBridge, ipcRenderer, type IpcRendererEvent } from 'electron';
contextBridge.exposeInMainWorld('desktop', {
  api: (method: string, ...args: unknown[]): Promise<unknown> => ipcRenderer.invoke('api', method, ...args),
  pickFolder: (): Promise<string | null> => ipcRenderer.invoke('pick-folder'),
  pickImages: (): Promise<unknown[]> => ipcRenderer.invoke('pick:images'),
  chatStart: (req: unknown): Promise<boolean> => ipcRenderer.invoke('chat:start', req),
  accountStatus: (provider: string): Promise<unknown> => ipcRenderer.invoke('account:status', provider),
  accountLogout: (provider: string): Promise<unknown> => ipcRenderer.invoke('account:logout', provider),
  accountLogin: (provider: string): Promise<boolean> => ipcRenderer.invoke('account:login', provider),
  accountReply: (provider: string, text: string): Promise<boolean> => ipcRenderer.invoke('account:reply', provider, text),
  accountCancel: (provider: string): Promise<boolean> => ipcRenderer.invoke('account:cancel', provider),
  readFile: (p: string): Promise<unknown> => ipcRenderer.invoke('file:read', p),
  openPath: (p: string): Promise<boolean> => ipcRenderer.invoke('file:open', p),
  onPaneOpen: (cb: (url: string) => void): (() => void) => { const h = (_e: IpcRendererEvent, url: string) => cb(url); ipcRenderer.on('pane:open', h); return () => ipcRenderer.removeListener('pane:open', h); },
  onAgentRequest: (cb: (r: unknown) => void): (() => void) => { const h = (_e: IpcRendererEvent, r: unknown) => cb(r); ipcRenderer.on('agent:request', h); return () => ipcRenderer.removeListener('agent:request', h); },
  agentRequestDone: (id: string, text: string): void => ipcRenderer.send('agent:request:done', id, text),
  onAppCommand: (cb: (c: unknown) => void): (() => void) => { const h = (_e: IpcRendererEvent, c: unknown) => cb(c); ipcRenderer.on('app:command', h); return () => ipcRenderer.removeListener('app:command', h); },
  appCommandDone: (id: string, result: unknown): void => ipcRenderer.send('app:command:done', id, result),
  onCommandDetails: (cb: (d: unknown) => void): (() => void) => { const h = (_e: unknown, d: unknown) => cb(d); ipcRenderer.on('command:details', h); return () => ipcRenderer.removeListener('command:details', h); },
  onAccountEvent: (cb: (e: unknown) => void): (() => void) => { const h = (_e: unknown, e: unknown) => cb(e); ipcRenderer.on('account:event', h); return () => ipcRenderer.removeListener('account:event', h); },
  appRestart: (): Promise<boolean> => ipcRenderer.invoke('app:restart'),
  appReset: (): Promise<boolean> => ipcRenderer.invoke('app:reset'),
  openExternal: (url: string): Promise<boolean> => ipcRenderer.invoke('open:external', url),
  usage: (provider: string, force?: boolean): Promise<unknown> => ipcRenderer.invoke('usage:get', provider, force),
  chatLive: (): Promise<unknown> => ipcRenderer.invoke('chat:live'),
  appReload: (): Promise<boolean> => ipcRenderer.invoke('app:reload'),
  chatRunning: (chatId: string): Promise<boolean> => ipcRenderer.invoke('chat:running', chatId),
  chatSteer: (chatId: string, text: string, images?: unknown): Promise<boolean> => ipcRenderer.invoke('chat:steer', chatId, text, images),
  chatStop: (chatId: string): Promise<boolean> => ipcRenderer.invoke('chat:stop', chatId),
  chatAnswer: (chatId: string, requestId: string, decision: string): Promise<boolean> => ipcRenderer.invoke('chat:answer', chatId, requestId, decision),
  onChatEvent: (cb: (ev: unknown) => void): (() => void) => { const h = (_e: IpcRendererEvent, ev: unknown) => cb(ev); ipcRenderer.on('chat:event', h); return () => ipcRenderer.removeListener('chat:event', h); },
  voiceOn: (on: boolean, who: string, provider?: string, ackModel?: string, stt?: unknown): Promise<unknown> => ipcRenderer.invoke('voice:on', on, who, provider, ackModel, stt),
  decisions: (useJev: boolean): Promise<unknown> => ipcRenderer.invoke('voice:decisions', useJev),
  command: (text: string, projects: unknown, currentId: string, speaker?: unknown): Promise<unknown> => ipcRenderer.invoke('voice:command', text, projects, currentId, speaker),
  thoughtDone: (text: string): Promise<unknown> => ipcRenderer.invoke('voice:done', text),
  debugList: (): Promise<unknown> => ipcRenderer.invoke('debug:list'),
  debugClear: (): Promise<boolean> => ipcRenderer.invoke('debug:clear'),
  welcomeAudio: (open: boolean): void => ipcRenderer.send('audio:welcome', open),
  miniDrag: (on: boolean): void => ipcRenderer.send('mini:drag', on),
  welcomeIntent: (text: string): Promise<unknown> => ipcRenderer.invoke('welcome:intent', text),
  debugPush: (kind: string, text: string): void => ipcRenderer.send('debug:push', kind, text),
  onDebug: (cb: (e: unknown) => void): (() => void) => { const h = (_e: IpcRendererEvent, ev: unknown) => cb(ev); ipcRenderer.on('debug:event', h); return () => ipcRenderer.removeListener('debug:event', h); },
  sttConfig: (model: string, vocabulary: string): Promise<boolean> => ipcRenderer.invoke('voice:stt', model, vocabulary),
  voiceStatus: (): Promise<unknown> => ipcRenderer.invoke('voice:status'),
  voiceModelInUse: (provider: string, preferred: string): Promise<string> => ipcRenderer.invoke('voice:model-in-use', provider, preferred),
  setupCheck: (): Promise<unknown> => ipcRenderer.invoke('setup:check'),
  wakeCheck: (wav: ArrayBuffer, phrase: string, language: string): Promise<unknown> => ipcRenderer.invoke('voice:wake', wav, phrase, language),
  transcribe: (wav: ArrayBuffer, language: string, quiet?: boolean, hint?: string, retry?: boolean): Promise<unknown> => ipcRenderer.invoke('voice:transcribe', wav, language, quiet, hint, retry),
  ack: (text: string): Promise<string> => ipcRenderer.invoke('voice:ack', text),
  understand: (text: string, provider: string, model: string, main: string, recent?: string, said?: string): Promise<string> => ipcRenderer.invoke('voice:understand', text, provider, model, main, recent, said),
  triage: (text: string, provider: string, model: string, main: string, task?: string): Promise<unknown> => ipcRenderer.invoke('voice:triage', text, provider, model, main, task),
  summarize: (asked: string, answer: string, provider: string, model: string, main: string): Promise<string> => ipcRenderer.invoke('voice:summarize', asked, answer, provider, model, main),
  speak: (text: string, voice: string, rate: number): Promise<ArrayBuffer | null> => ipcRenderer.invoke('voice:speak', text, voice, rate),
  cancelSpeech: (): Promise<boolean> => ipcRenderer.invoke('voice:cancel'),
  voiceState: (st: unknown): void => ipcRenderer.send('voice:state', st),
  onVoiceState: (cb: (st: unknown) => void): (() => void) => { const h = (_e: IpcRendererEvent, st: unknown) => cb(st); ipcRenderer.on('voice:state', h); return () => ipcRenderer.removeListener('voice:state', h); },
  voiceCmd: (cmd: string): void => ipcRenderer.send('voice:cmd', cmd),
  voiceType: (text: string): void => ipcRenderer.send('voice:type', text),
  onVoiceType: (cb: (text: string) => void): (() => void) => { const h = (_e: IpcRendererEvent, t: string) => cb(t); ipcRenderer.on('voice:type', h); return () => ipcRenderer.removeListener('voice:type', h); },
  miniSize: (w: number): void => ipcRenderer.send('mini:size', w),
  onVoiceCmd: (cb: (cmd: string) => void): (() => void) => { const h = (_e: IpcRendererEvent, cmd: string) => cb(cmd); ipcRenderer.on('voice:cmd', h); return () => ipcRenderer.removeListener('voice:cmd', h); },
  platform: process.platform,
});
